### ISSUE TITLE
Using build.sh to build tensorflow 1.5

### ISSUE THREAD

**Issue by r1d1** [leggedrobotics/tensorflow-cpp#6]
Using your 1.15.2 build, I experienced an Illegal Instruction error while running Tensorflow-based code. It seems to be due to the AVX instruction set constraint coming with 1.6.
To overcome that, I tried to use your build.sh script to build tensorflow 1.5. I installed bazel 0.8.0 and made a copy of the tensorflow/bin/r1.15 folder into a r1.5 folder (in bin too).
I modified the build.sh to point to 1.5 ; set the bazel version to 0.8.0 ; variant to CPU (see attached file). I didn't modify the tf_configure* files.
When I try to run the script, line 88 (93 in my version of the script) usually fails
https://github.com/leggedrobotics/tensorflow-cpp/blob/604bb4d3eacdd1315447eddf47e687c0e147a2a1/tensorflow/bin/r1.15/build.sh#L88

`ERROR: no such target '//third_party/eigen3:install_eigen_headers': target 'install_eigen_headers' not declared in package 'third_party/eigen3' defined by /home/<user>/.tensorflow/src/third_party/eigen3/BUILD
`

I can comment the last two elements (//tensorflow:install_headers //third_party/eigen3:install_eigen_headers) which seems to allow Tensorflow to build, but no include folder is generated (not sure the headers are properly built).

Did I miss a prerequisite ? I'm not so familiar with (building) tensorflow.

[build.sh.txt](https://github.com/leggedrobotics/tensorflow-cpp/files/6149672/build.sh.txt)

**Comment by r1d1** [comment]
Hello,
can anyone help ?
Thanks

**Comment by vastsoun** [comment]
Apologies for the late reply, I was AFK (on vacation). 

Please clarify the following: 
1. Which version of tensorflow do you actually need? This repo provides binaries and recipes only for 1.13.* + 1.15.* at the moment.
2. Do you mean that you want to actually build specifically for tensorflow `1.5`?
3. Do you also have specific requirements regarding optimization flags? i.e. Are you incapable of using AVX instructions and other optimizations?

**Comment by r1d1** [comment]
For now, we need tensorflow 1.5 CPU no AVX due to the incompatibility of tensorflow with our CPU. We used version 1.15.2 that you provide but it triggers an Illegal Instruction at runtime, which we think is due to the use of AVX instructions (although I'm not fully sure of that).

**Comment by vastsoun** [comment]
Unfortunately we don't provide support for `r1.5`, however maybe I can help in describing the (rough) steps needed to build it  on your own: 

0. If you need CPU-only this is gonna makes things easier (thankfully). First start by checking the version of [bazel](https://www.tensorflow.org/install/source#cpu). I think this you have figured out already so you probably can skip it.
1. Next, checkout branch `r1.5`. NOTE: not the tag, the release `r*.*` branch for 1.5.
2. Next you need to run the `configure` script which will generate the `.tf_configure.bazelrc` file. Here you can add/specify more flags to tailor it to your needs.
3. To build the library binaries you need to run the `bazel build //tensorflow:libtensorflow_cc.so //tensorflow:install_headers` command. The first target is mandatory but the second one is useful for generating and concentrating all the header files to one place in the bazel build/output directories.
4. You then need to manually extract the library binaries and the headers and organize them in a directory structure as I've done for the other versions. This will ensure that the CMake files will find all library files in the expected locations.
5. TensorFlow also needs a specially patched version of Eigen3 in order to work. This means that everything else also using Eigen3 that would interface with TF in the same build also needs that specific version. To achieve this you need to look for the `eigen_archive` http target and make sure to download/clone this manually, and apply any patches if necessary (you will see Bazel recipes in the `third_party/eigen3/BUILD` and `tensorflow/workspace.bzl` files that will specify what files need to be overwritten). You should then install, using CMake, this version of Eigen3 in a place where CMake can find it. But be careful because this will conflict with the globally installed version of Eigen3 coming from the `sudo apt install libeigen3-dev` package. I recommend installing the special version in a local workspace or in your user's `~/.local` directory.

Unfortunately I do not have any capacity at the moment to provide this out-of-the-box for you. So I'll have to leave it to you to interpret and realize the instructions I've outlined above. Please continue posting questions to this thread if necessary.
